config/routes.rb
Rails.application.routes.draw do
  match 'todos/list', :controller => 'todos', :action => 'list', via: :get
	get 'todos', to: 'todos#index'
	get 'todos/new'
	post 'todos', to: 'todos#create'
	get 'todos/:id', to: 'todos#show', as: 'todo'
	get 'todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
	patch 'todos/:id', to: 'todos#update'
	delete 'todos/:id', to: 'todos#destroy'
	get 'todos/:id/complete', to: 'todos#complete', as: 'todo_complete'
	get 'todos/list', to: 'todos#list'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :complete]  
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
	end

	def show
	end

	def edit
	end

	def update
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
		@todo.destroy
		redirect_to todos_path
	end

	def complete
		@todo.completed = true
		@todo.save
		redirect_to todos_path
	end

	def list
		@todos = Todo.all
	end

	private
	def todo_params
		params.require(:todo).permit(:description, :completed)
	end

	def find_post
		@todo = Todo.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Boostrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>

    <div class="mt-4 p-5 text-center"> 
      <%= yield %> 
    </div>
    
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local:true do |f| %>
	<h1> <%= f.label :description, "Descripción" %> </h1>
	<p> <%= f.text_area :description %> </p>
	
	<%= f.submit "Enviar" %>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li><%= link_to 'Index', todos_path %></li> 
      <li class="pl-4"><%= link_to 'List', todos_list_path %></li> 
      <li class="pl-4"><%= link_to 'Formulario de creación', todos_new_path %></li> 
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<div class="jumbotron">
	<% @todos.each do |todo| %>
		<div class="p-3">
			<h3> <%= todo.description %> </h3>	
			<hr>			
		</div>
		<button type="button" class="btn btn-success btn-lg"> 
			<%= link_to 'Marcar como completado', todo_complete_path(todo), class: "color-link" %> 
		</button>
		<button type="button" class="btn btn-info btn-lg"> 
			<%= link_to 'Mostrar', todo, class: "color-link" %> 
		</button>
		<button type="button" class="btn btn-warning btn-lg"> 
			<%= link_to 'Editar', todo_edit_path(todo), class: "new-color" %> 
		</button>
		<button type="button" class="btn btn-danger btn-lg"> 
			<%= link_to "Borrar", todo, method: :delete, class: "color-link" %> 
		</button>
		<br>
	<% end %>
	<h1><button type="button" class="badge badge-warning mt-4">
		<%= link_to 'Crear Todo', todos_new_path, class: "new-color" %>
	</button></h1>
</div>

app/views/todos/list.html.erb
<div class="row">
	<div class="col-md-6 bg-success" >
		<h1> Completed </h1>
		<% @todos.each do |t| %>
			<% if t.completed == true %>
				<ul class="list-group">
					<li class="list-group-item"><%= t.description %></li>
				</ul>
			<% end %>
		<% end %>
	</div>

	<div class="col-md-6 bg-danger">
		<h1 class="text-white"> Not Completed </h1>
		<% @todos.each do |t| %>
			<% if t.completed == nil %>
				<ul class="list-group">
					<li class="list-group-item"><%= t.description %></li>
				</ul>
			<% end %>
		<% end %>
	</div>
</div>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<p><%= @todo.description %></p>